 name: Deploy to Netlify

   on:
     push:
       branches:
         - main

   jobs:
     build:
       runs-on: ubuntu-latest

       steps:
         - name: Checkout code
           uses: actions/checkout@v2

         - name: Setup Node.js
           uses: actions/setup-node@v2
           with:
             node-version: '22'

         - name: Install dependencies
           run: npm install

         - name: Build the project
           run: npm run build

         - name: Deploy to Netlify
           run: |
             npm install -g netlify-cli
             netlify deploy --prod --dir=build --auth=4e720c9c30e1a63a0fa241dfcb1d456814c50bc6 --site=5af291e1-0601-4cc3-9192-b0283f4c3a27
           env:
             NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}