 name: Deploy to Netlify

   on:
     push:
       branches:
         - main

   jobs:
     build:
       runs-on: ubuntu-latest

       steps:
         - name: Checkout code
           uses: actions/checkout@v2

         - name: Setup Node.js
           uses: actions/setup-node@v2
           with:
             node-version: '22'

         - name: Install dependencies
           run: npm install

         - name: Build the project
           run: npm run build

         - name: Deploy to Netlify
           run: |
             npm install -g netlify-cli
             netlify deploy --prod --dir=build --auth=$NETLIFY_AUTH_TOKEN --site=your-netlify-site-id
           env:
             NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}